name: Neovim

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Install dependencies
        run: |
          pip install git+https://github.com/kazukazuinaina/vimstartup
      - name: Check Vim version
        run: |
          nvim --version
      - name: Run test
        run: |
          python test/test_neovim.py
